/* Auto-generated from radar_ui.html — DO NOT EDIT */
#pragma once
#include <stddef.h>

static const char radar_ui_html[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no\">\n"
    "<title>RD-03D Tactical Radar</title>\n"
    "<link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>📡</text></svg>\">\n"
    "<style>\n"
    "*{margin:0;padding:0;box-sizing:border-box}\n"
    ":root{\n"
    "  --bg:#020a04;\n"
    "  --bg-card:rgba(4,20,8,0.85);\n"
    "  --border:#00ff41;\n"
    "  --text:#00ff41;\n"
    "  --font-mono:'Courier New',Courier,monospace;\n"
    "  --font-sans:var(--font-mono);\n"
    "}\n"
    "body{background:var(--bg);color:var(--text);font-family:var(--font-sans);height:100vh;height:100dvh;overflow:hidden}\n"
    ".app{display:flex;flex-direction:column;height:100%}\n"
    "\n"
    "/* ===== Header ===== */\n"
    ".header{display:flex;justify-content:space-between;align-items:center;padding:10px 20px;\n"
    "  background:var(--bg-card);border-bottom:2px solid var(--border);z-index:10;flex-shrink:0}\n"
    ".logo{display:flex;align-items:center;gap:10px;font-weight:bold;font-size:16px;letter-spacing:2px}\n"
    ".header-right{display:flex;align-items:center;gap:16px}\n"
    ".status-badge{padding:4px 12px;border:1px solid var(--border);font-size:12px;font-weight:bold;text-transform:uppercase;background:rgba(0,255,65,0.1)}\n"
    ".status-badge.disconnected{border-color:red;color:red;background:rgba(255,0,0,0.1)}\n"
    ".uptime{font-size:13px;letter-spacing:1px}\n"
    "\n"
    "/* ===== Main Layout ===== */\n"
    ".main{display:flex;flex:1;overflow:hidden;min-height:0}\n"
    ".radar-section{flex:1;display:flex;align-items:center;justify-content:center;padding:16px;min-width:0;position:relative}\n"
    ".radar-wrapper{position:relative;width:100%;height:100%;display:flex;align-items:center;justify-content:center}\n"
    ".radar-container{position:relative;width:100%;height:100%;overflow:hidden;border:2px solid var(--border);background:var(--bg)}\n"
    "#radarCanvas{display:block;width:100%;height:100%}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"app\">\n"
    "  <header class=\"header\">\n"
    "    <div class=\"logo\">[ RD-03D TACTICAL HUD ]</div>\n"
    "    <div class=\"header-right\">\n"
    "      <div class=\"status-badge disconnected\" id=\"connStatus\">LINK LOST</div>\n"
    "      <div class=\"uptime\" id=\"uptime\">00:00:00</div>\n"
    "    </div>\n"
    "  </header>\n"
    "\n"
    "  <main class=\"main\">\n"
    "    <section class=\"radar-section\">\n"
    "      <div class=\"radar-wrapper\">\n"
    "        <div class=\"radar-container\">\n"
    "          <canvas id=\"radarCanvas\"></canvas>\n"
    "        </div>\n"
    "      </div>\n"
    "    </section>\n"
    "  </main>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "(function(){\n"
    "\"use strict\";\n"
    "\n"
    "const MAX_RANGE   = 8000;\n"
    "const FOV_HALF    = 60;\n"
    "const TRAIL_LEN   = 10;\n"
    "const COLOR       = '#00ff41';\n"
    "\n"
    "let connected   = false;\n"
    "let targets     = [{a:0},{a:0},{a:0}];\n"
    "let stats       = {ok:0, bad:0, up:0};\n"
    "let trails      = {};\n"
    "let ws          = null;\n"
    "let retryDelay  = 1000;\n"
    "\n"
    "const canvas     = document.getElementById('radarCanvas');\n"
    "const ctx        = canvas.getContext('2d');\n"
    "const connEl     = document.getElementById('connStatus');\n"
    "const uptimeEl   = document.getElementById('uptime');\n"
    "\n"
    "function resize(){\n"
    "  const box  = canvas.parentElement;\n"
    "  const dpr  = window.devicePixelRatio || 1;\n"
    "  canvas.width  = box.clientWidth * dpr;\n"
    "  canvas.height = box.clientHeight * dpr;\n"
    "  ctx.setTransform(dpr,0,0,dpr,0,0);\n"
    "}\n"
    "\n"
    "function mm2px(xmm, ymm){\n"
    "  const cw = canvas.width / (window.devicePixelRatio||1);\n"
    "  const ch = canvas.height / (window.devicePixelRatio||1);\n"
    "  // Bottom center\n"
    "  const originX = cw / 2;\n"
    "  const originY = ch - 20;\n"
    "  // Fit 8000mm in Y\n"
    "  const scale = (ch - 40) / MAX_RANGE;\n"
    "  return { x: originX + xmm * scale, y: originY - ymm * scale };\n"
    "}\n"
    "\n"
    "function draw(){\n"
    "  const cw = canvas.width / (window.devicePixelRatio||1);\n"
    "  const ch = canvas.height / (window.devicePixelRatio||1);\n"
    "  ctx.clearRect(0,0,cw,ch);\n"
    "\n"
    "  // Background Grid\n"
    "  ctx.strokeStyle = 'rgba(0,255,65,0.15)';\n"
    "  ctx.lineWidth = 1;\n"
    "  const gridSize = 50;\n"
    "  for(let x = 0; x < cw; x += gridSize){ ctx.beginPath(); ctx.moveTo(x,0); ctx.lineTo(x,ch); ctx.stroke(); }\n"
    "  for(let y = 0; y < ch; y += gridSize){ ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(cw,y); ctx.stroke(); }\n"
    "\n"
    "  const originX = cw / 2;\n"
    "  const originY = ch - 20;\n"
    "\n"
    "  // FOV Trapezoid\n"
    "  const fovRad = FOV_HALF * Math.PI / 180;\n"
    "  ctx.beginPath();\n"
    "  ctx.moveTo(originX, originY);\n"
    "  const pLeft = mm2px(-MAX_RANGE * Math.tan(fovRad), MAX_RANGE);\n"
    "  const pRight = mm2px(MAX_RANGE * Math.tan(fovRad), MAX_RANGE);\n"
    "  ctx.lineTo(pLeft.x, pLeft.y);\n"
    "  ctx.lineTo(pRight.x, pRight.y);\n"
    "  ctx.closePath();\n"
    "  ctx.strokeStyle = 'rgba(0,255,65,0.4)';\n"
    "  ctx.lineWidth = 2;\n"
    "  ctx.stroke();\n"
    "  ctx.fillStyle = 'rgba(0,255,65,0.05)';\n"
    "  ctx.fill();\n"
    "\n"
    "  // Range lines (every 2m)\n"
    "  for(let r=2000; r<=MAX_RANGE; r+=2000){\n"
    "    const yPx = mm2px(0, r).y;\n"
    "    ctx.beginPath();\n"
    "    ctx.moveTo(0, yPx);\n"
    "    ctx.lineTo(cw, yPx);\n"
    "    ctx.strokeStyle = 'rgba(0,255,65,0.3)';\n"
    "    ctx.setLineDash([5,5]);\n"
    "    ctx.stroke();\n"
    "    ctx.setLineDash([]);\n"
    "    ctx.font = '10px Courier New';\n"
    "    ctx.fillStyle = COLOR;\n"
    "    ctx.fillText((r/1000)+'m', 5, yPx - 5);\n"
    "  }\n"
    "\n"
    "  // Sensor origin\n"
    "  ctx.beginPath();\n"
    "  ctx.arc(originX, originY, 6, 0, Math.PI*2);\n"
    "  ctx.fillStyle = COLOR;\n"
    "  ctx.fill();\n"
    "\n"
    "  // Target Trails\n"
    "  for(const id in trails){\n"
    "    const tr = trails[id];\n"
    "    for(let i=0;i<tr.length;i++){\n"
    "      const a = (i+1)/tr.length * 0.5;\n"
    "      const sz = 2;\n"
    "      const p = mm2px(tr[i].x, tr[i].y);\n"
    "      ctx.beginPath(); ctx.rect(p.x-sz,p.y-sz,sz*2,sz*2);\n"
    "      ctx.fillStyle = `rgba(0,255,65,${a})`;\n"
    "      ctx.fill();\n"
    "    }\n"
    "  }\n"
    "\n"
    "  // Targets\n"
    "  targets.forEach(function(t){\n"
    "    if(!t.a) return;\n"
    "    const p = mm2px(t.x, t.y);\n"
    "\n"
    "    // Calculate movement direction\n"
    "    let angle = -Math.PI/2;\n"
    "    if(Math.abs(t.s) > 1.0){\n"
    "        angle = Math.atan2(-t.y, t.x);\n"
    "        if(t.s < 0) angle += Math.PI;\n"
    "    }\n"
    "\n"
    "    // Draw upright triangle\n"
    "    ctx.save();\n"
    "    ctx.translate(p.x, p.y);\n"
    "    ctx.beginPath();\n"
    "    ctx.moveTo(0, -10);\n"
    "    ctx.lineTo(7, 7);\n"
    "    ctx.lineTo(-7, 7);\n"
    "    ctx.closePath();\n"
    "    ctx.fillStyle = COLOR;\n"
    "    ctx.fill();\n"
    "    ctx.restore();\n"
    "\n"
    "    // Speed vector line\n"
    "    if(Math.abs(t.s) > 1.0){\n"
    "        const vLen = Math.max(20, Math.min(Math.abs(t.s) * 0.8, 100));\n"
    "        const endX = p.x + Math.cos(angle) * vLen;\n"
    "        const endY = p.y + Math.sin(angle) * vLen;\n"
    "        \n"
    "        ctx.beginPath();\n"
    "        ctx.moveTo(p.x, p.y);\n"
    "        ctx.lineTo(endX, endY);\n"
    "        ctx.strokeStyle = COLOR;\n"
    "        ctx.lineWidth = 1.5;\n"
    "        ctx.stroke();\n"
    "        \n"
    "        ctx.save();\n"
    "        ctx.translate(endX, endY);\n"
    "        ctx.rotate(angle);\n"
    "        ctx.beginPath();\n"
    "        ctx.moveTo(4, 0);\n"
    "        ctx.lineTo(-4, 4);\n"
    "        ctx.lineTo(-4, -4);\n"
    "        ctx.closePath();\n"
    "        ctx.fillStyle = COLOR;\n"
    "        ctx.fill();\n"
    "        ctx.restore();\n"
    "    }\n"
    "\n"
    "    // Target characteristics block\n"
    "    ctx.font = 'bold 12px Courier New';\n"
    "    ctx.fillStyle = COLOR;\n"
    "    ctx.fillText('TRK-'+t.id, p.x + 14, p.y - 15);\n"
    "    \n"
    "    ctx.font = '10px Courier New';\n"
    "    ctx.fillStyle = 'rgba(0,255,65,0.7)';\n"
    "    ctx.fillText('POS: '+(t.x/10).toFixed(0)+','+(t.y/10).toFixed(0)+'cm', p.x + 14, p.y - 2);\n"
    "    ctx.fillText('DST: '+(t.d/1000).toFixed(2)+'m', p.x + 14, p.y + 10);\n"
    "    ctx.fillText('SPD: '+t.s.toFixed(1)+'cm/s', p.x + 14, p.y + 22);\n"
    "  });\n"
    "}\n"
    "\n"
    "function animate(){\n"
    "  draw();\n"
    "  requestAnimationFrame(animate);\n"
    "}\n"
    "\n"
    "function connectWS(){\n"
    "  ws = new WebSocket('ws://'+location.host+'/ws');\n"
    "  ws.onopen = function(){\n"
    "    connected=true; retryDelay=1000;\n"
    "    connEl.className='status-badge';\n"
    "    connEl.textContent='LINK SECURE';\n"
    "  };\n"
    "  ws.onclose = function(){\n"
    "    connected=false;\n"
    "    connEl.className='status-badge disconnected';\n"
    "    connEl.textContent='LINK LOST';\n"
    "    setTimeout(connectWS, retryDelay);\n"
    "    retryDelay = Math.min(retryDelay*2, 10000);\n"
    "  };\n"
    "  ws.onerror = function(){ ws.close(); };\n"
    "  ws.onmessage = function(ev){\n"
    "    try{ processData(JSON.parse(ev.data)); }catch(e){}\n"
    "  };\n"
    "}\n"
    "\n"
    "function processData(d){\n"
    "  targets = d.t;\n"
    "  stats.ok  = d.ok;\n"
    "  stats.bad = d.bad;\n"
    "  stats.up  = d.up;\n"
    "\n"
    "  var activeIds = {};\n"
    "  targets.forEach(function(t){\n"
    "    if(!t.a) return;\n"
    "    activeIds[t.id] = true;\n"
    "    if(!trails[t.id]) trails[t.id]=[];\n"
    "    trails[t.id].push({x:t.x, y:t.y});\n"
    "    if(trails[t.id].length > TRAIL_LEN) trails[t.id].shift();\n"
    "  });\n"
    "  for(var id in trails){\n"
    "    if(!activeIds[id]){\n"
    "      trails[id].shift();\n"
    "      if(!trails[id].length) delete trails[id];\n"
    "    }\n"
    "  }\n"
    "  updatePanel();\n"
    "}\n"
    "\n"
    "function updatePanel(){\n"
    "  var sec = Math.floor(stats.up/1000);\n"
    "  var h = Math.floor(sec/3600), m = Math.floor((sec%3600)/60), s = sec%60;\n"
    "  uptimeEl.textContent = 'T+'+pad(h)+':'+pad(m)+':'+pad(s);\n"
    "}\n"
    "\n"
    "function pad(n){ return n<10 ? '0'+n : ''+n; }\n"
    "\n"
    "window.addEventListener('load', function(){\n"
    "  resize();\n"
    "  connectWS();\n"
    "  requestAnimationFrame(animate);\n"
    "});\n"
    "window.addEventListener('resize', resize);\n"
    "\n"
    "})();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n"
;

static const size_t radar_ui_html_len = sizeof(radar_ui_html) - 1;
